# See https://docs.redoc.ly/cli/configuration/ for more information.
apiDefinitions:
  main: openapi/openapi.yaml
lint:
  rules:
    no-unused-schemas: warning
referenceDocs:
  htmlTemplate: ./docs/index.html
  theme:
    colors:
      primary:
        main: "#32329f"
    sidebar:
      backgroundColor: "#1e0d53"
      textColor: "#cbcbcb"

